### ISSUE TITLE
Container image MAKE errors while building gcc-9.1.0-7.cm1.src.rpm

### ISSUE THREAD

**Issue by smallheath1919** [microsoft/CBL-Mariner#1223]
On running `sudo make image CONFIG_FILE=./imageconfigs/core-container.json REBUILD_TOOLS=y SOURCE_URL=https://cblmarinerstorage.blob.core.windows.net/sources/core`

I get the following error when building `gcc-9.1.0-7.cm1.src.rpm`: 

```
INFO[0000] Building (gcc-9.1.0-7.cm1.src.rpm).
INFO[1800] Heartbeat: still building (gcc-9.1.0-7.cm1.src.rpm).
WARN[3344] Failed package build attempt (/root/CBL-Mariner/build/INTERMEDIATE_SRPMS/gcc-9.1.0-7.cm1.src.rpm), error (exit status 1)
ERRO[3344] Failed to build SRPM '/root/CBL-Mariner/build/INTERMEDIATE_SRPMS/gcc-9.1.0-7.cm1.src.rpm'. For details see log file: /root/CBL-Mariner/build/logs/pkggen/rpmbuilding/gcc-9.1.0-7.cm1.src.rpm.log.
PANI[3344] exit status 1
panic: (*logrus.Entry) 0xc0000a2230

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0000a3880, 0xc00039eae0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x345
github.com/sirupsen/logrus.(*Entry).Log(0xc0000a2000, 0x0, 0xc000453c28, 0x1, 0x1)
        /root/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xf0
github.com/sirupsen/logrus.(*Entry).Logln(0xc0000a2000, 0xc000000000, 0xc000453cc0, 0x1, 0x1)
        /root/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:378 +0xd6
github.com/sirupsen/logrus.(*Logger).Logln(0xc0000a3880, 0xc000000000, 0xc000453cc0, 0x1, 0x1)
        /root/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:240 +0x7e
github.com/sirupsen/logrus.(*Logger).Panicln(...)
        /root/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:281
microsoft.com/pkggen/internal/logger.PanicOnError(0x677be0, 0xc00040bca0, 0xc000453e00, 0x3, 0x3)
        /root/CBL-Mariner/toolkit/tools/internal/logger/log.go:122 +0xfa
main.main()
        /root/CBL-Mariner/toolkit/tools/pkgworker/pkgworker.go:96 +0x84e
```
Digging into the build logs I can see:

```
time="2021-08-01T00:00:10Z" level=debug msg="Processing files: libgcc-atomic-9.1.0-7.cm1.x86_64"
time="2021-08-01T00:00:10Z" level=debug msg="Finding  Provides: /usr/lib/rpm/find-provides"
time="2021-08-01T00:00:10Z" level=debug msg="Finding  Requires(interp): "
time="2021-08-01T00:00:10Z" level=debug msg="Finding  Requires(rpmlib): "
time="2021-08-01T00:00:10Z" level=debug msg="Finding  Requires(verify): "
time="2021-08-01T00:00:10Z" level=debug msg="Finding  Requires(pre): "
time="2021-08-01T00:00:10Z" level=debug msg="Finding  Requires(post): "
time="2021-08-01T00:00:10Z" level=debug msg="Finding  Requires(preun): "
time="2021-08-01T00:00:10Z" level=debug msg="Finding  Requires(postun): "
time="2021-08-01T00:00:10Z" level=debug msg="Finding  Requires(pretrans): "
time="2021-08-01T00:00:10Z" level=debug msg="Finding  Requires(posttrans): "
time="2021-08-01T00:00:10Z" level=debug msg="Finding  Requires: /usr/lib/rpm/find-requires"
time="2021-08-01T00:00:10Z" level=debug msg="Finding  Conflicts: "
time="2021-08-01T00:00:10Z" level=debug msg="Finding  Obsoletes: "
time="2021-08-01T00:00:10Z" level=debug msg="Finding  Recommends: "
time="2021-08-01T00:00:10Z" level=debug msg="Finding  Suggests: "
time="2021-08-01T00:00:10Z" level=debug msg="Finding  Supplements: "
time="2021-08-01T00:00:10Z" level=debug msg="Finding  Enhances: "
time="2021-08-01T00:00:10Z" level=debug msg="error: File not found: /usr/src/mariner/BUILDROOT/gcc-9.1.0-7.cm1.x86_64/usr/lib/libcc1.*"
time="2021-08-01T00:00:10Z" level=debug msg="    Macro expanded in comment on line 22: %{with_check}"
time="2021-08-01T00:00:10Z" level=debug
time="2021-08-01T00:00:10Z" level=debug msg="    Deprecated external dependency generator is used!"
time="2021-08-01T00:00:10Z" level=debug msg="    Deprecated external dependency generator is used!"
time="2021-08-01T00:00:10Z" level=debug msg="    Deprecated external dependency generator is used!"
time="2021-08-01T00:00:10Z" level=debug msg="    Deprecated external dependency generator is used!"
time="2021-08-01T00:00:10Z" level=debug msg="    File not found: /usr/src/mariner/BUILDROOT/gcc-9.1.0-7.cm1.x86_64/usr/lib/libcc1.*"
time="2021-08-01T00:00:10Z" level=debug msg="Provides: libatomic.so.1()(64bit) libatomic.so.1(LIBATOMIC_1.0)(64bit) libatomic.so.1(LIBATOMIC_1.1)(64bit) libatomic.so.1(LIBATOMIC_1.2)(64bit) libgcc-atomic = 9.1.0-7.cm1 libgcc-atomic(x86-64) = 9.1.0-7.cm1"
time="2021-08-01T00:00:10Z" level=debug msg="Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1"
time="2021-08-01T00:00:10Z" level=debug msg="Requires: libc.so.6()(64bit) libc.so.6(GLIBC_2.14)(64bit) libc.so.6(GLIBC_2.2.5)(64bit) libc.so.6(GLIBC_2.3.4)(64bit) libc.so.6(GLIBC_2.4)(64bit) libpthread.so.0()(64bit) libpthread.so.0(GLIBC_2.2.5)(64bit)"
time="2021-08-01T00:00:10Z" level=debug msg="Processing files: libgcc-devel-9.1.0-7.cm1.x86_64"
time="2021-08-01T00:00:10Z" level=debug
time="2021-08-01T00:00:10Z" level=debug
time="2021-08-01T00:00:10Z" level=debug msg="RPM build errors:"
time="2021-08-01T00:00:10Z" level=debug msg="Exiting Chroot"
time="2021-08-01T00:00:10Z" level=debug msg="Unmounting (/root/CBL-Mariner/build/worker/chroot/gcc-9.1.0-7.cm1/upstream-cached-rpms)"
time="2021-08-01T00:00:10Z" level=debug msg="Unmounting (/root/CBL-Mariner/build/worker/chroot/gcc-9.1.0-7.cm1/sys)"
time="2021-08-01T00:00:10Z" level=debug msg="Unmounting (/root/CBL-Mariner/build/worker/chroot/gcc-9.1.0-7.cm1/run)"
time="2021-08-01T00:00:10Z" level=debug msg="Unmounting (/root/CBL-Mariner/build/worker/chroot/gcc-9.1.0-7.cm1/proc)"
time="2021-08-01T00:00:10Z" level=debug msg="Unmounting (/root/CBL-Mariner/build/worker/chroot/gcc-9.1.0-7.cm1/localrpms)"
time="2021-08-01T00:00:10Z" level=debug msg="Unmounting (/root/CBL-Mariner/build/worker/chroot/gcc-9.1.0-7.cm1/dev/pts)"
time="2021-08-01T00:00:10Z" level=debug msg="Unmounting (/root/CBL-Mariner/build/worker/chroot/gcc-9.1.0-7.cm1/dev)"
time="2021-08-01T00:00:16Z" level=warning msg="Failed package build attempt (/root/CBL-Mariner/build/INTERMEDIATE_SRPMS/gcc-9.1.0-7.cm1.src.rpm), error (exit status 1)"
time="2021-08-01T00:00:16Z" level=error msg="Failed to build SRPM '/root/CBL-Mariner/build/INTERMEDIATE_SRPMS/gcc-9.1.0-7.cm1.src.rpm'. For details see log file: /root/CBL-Mariner/build/logs/pkggen/rpmbuilding/gcc-9.1.0-7.cm1.src.rpm.log."
time="2021-08-01T00:00:16Z" level=panic msg="exit status 1"
```

**Comment by zdyxry** [comment]
I got the same error.

Env: 
```
yiran@yiran-ubuntu:~/CBL-Mariner/build$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
yiran@yiran-ubuntu:~/CBL-Mariner/build$ uname -a
Linux yiran-ubuntu 5.4.0-80-generic #90~18.04.1-Ubuntu SMP Tue Jul 13 19:40:02 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by JoeGilkey** [comment]
I'm getting this error as well.

**Comment by mattmceuen** [comment]
Same here.

**Comment by aostapenko** [comment]
I guess we still want it to work. It's good with https://github.com/microsoft/CBL-Mariner/pull/1835
