### ISSUE TITLE
Error Building VHD/VHDX on Ubuntu

### ISSUE THREAD

**Issue by TylerJaacks** [microsoft/CBL-Mariner#1240]
```
tylerjaacks@tylerjaacks-ubuntu:~/CBL-Mariner/toolkit$ sudo make image REBUILD_TOOLS=y REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/full.json
[sudo] password for tylerjaacks: 
mkdir -p /home/tylerjaacks/CBL-Mariner/build/imagegen/full/imager_output && \
rm -rf /home/tylerjaacks/CBL-Mariner/build/imagegen/full/imager_output/* && \
/home/tylerjaacks/CBL-Mariner/toolkit/out/tools/imager \
	--build-dir /home/tylerjaacks/CBL-Mariner/build/imagegen/full/workspace \
	--input ./imageconfigs/full.json \
	--base-dir=./imageconfigs/ \
	--log-level=info \
	--log-file=/home/tylerjaacks/CBL-Mariner/build/logs/imggen/imager.log \
	--local-repo /home/tylerjaacks/CBL-Mariner/build/imagegen/full/package_repo \
	--tdnf-worker /home/tylerjaacks/CBL-Mariner/build/worker/worker_chroot.tar.gz \
	--repo-file=/home/tylerjaacks/CBL-Mariner/toolkit/resources/manifests/image/local.repo \
	--assets /home/tylerjaacks/CBL-Mariner/toolkit/resources/assets/ \
	--output-dir /home/tylerjaacks/CBL-Mariner/build/imagegen/full/imager_output && \
touch /home/tylerjaacks/CBL-Mariner/build/make_status/imager_disk_output.flag
INFO[0000] Building system configuration (CBL-Mariner Full) 
INFO[0000] Creating rootfs                              
INFO[0000] Rootfs is including a kernel (kernel)        
INFO[0004] HidepidDisabled is false.                    
WARN[0006] using empty dict to provide pw_dict          
WARN[0007] warning: /installroot/mariner-release-1.0-19.cm1.noarch.rpm: Header V4 RSA/SHA256 Signature, key ID 3135ce90: NOKEY 
WARN[0013] using empty dict to provide pw_dict          
WARN[0128] failed to link /usr/lib/libnssckbi.so -> /etc/alternatives/libnssckbi.so.x86_64: /usr/lib/libnssckbi.so exists and it is not a symlink 
WARN[0159] switching pw_dict to cracklib-dicts          
WARN[0159] Running in chroot, ignoring request: start   
WARN[0160] Running in chroot, ignoring request: daemon-reload 
WARN[0160] Running in chroot, ignoring request: start   
WARN[0160] gpg: directory '/root/.gnupg' created        
WARN[0160] gpg: keybox '/root/.gnupg/pubring.kbx' created 
WARN[0160] gpg: /root/.gnupg/trustdb.gpg: trustdb created 
WARN[0160] gpg: key EB3E94ADBE1229CF: public key "Microsoft (Release signing) <gpgsecurity@microsoft.com>" imported 
WARN[0160] gpg: Total number processed: 1               
WARN[0160] gpg:               imported: 1               
WARN[0160] gpg: key 0CD9FED33135CE90: public key "Mariner RPM Release Signing <marinerrpmprod@microsoft.com>" imported 
WARN[0160] gpg: Total number processed: 1               
WARN[0160] gpg:               imported: 1               
WARN[0161] initrd generation of kernel 5.10.42.1-3.cm1 will be triggered later 
WARN[0161] initramfs (re)generation triggerin 1 1 2.0-8.cm1 
WARN[0161] initramfs 2.0-8.cm1 posttrans                
INFO[0167] Proceeding to cleanup extra files in chroot /home/tylerjaacks/CBL-Mariner/build/imagegen/full/workspace/setuproot. 
INFO[0167] Cleaning up directory /tmp/additionalfiles   
INFO[0167] Cleaning up directory /tmp/postinstall       
INFO[0167] Cleaning up directory /tmp/sshpubkeys        
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.buildSystemConfig(0x0, 0x0, 0x0, 0x0, 0x0, 0xc0000175e0, 0x10, 0xc000090480, 0x4, 0x4, ...)
	/home/tylerjaacks/CBL-Mariner/toolkit/tools/imager/imager.go:225 +0x20b2
main.main()
	/home/tylerjaacks/CBL-Mariner/toolkit/tools/imager/imager.go:72 +0x408
make: *** [/home/tylerjaacks/CBL-Mariner/toolkit/scripts/imggen.mk:118: /home/tylerjaacks/CBL-Mariner/build/make_status/imager_disk_output.flag] Error 2
```

**Comment by christopherco** [comment]
Hi @TylerJaacks, to build a VHD, please run the `make image` target with `CONFIG_FILE=./imageconfigs/core-legacy.json`. To build a VHDX, please run the build with `CONFIG_FILE=./imageconfigs/core-efi.json`.

The `full.json` is an image definition for creating an ISO and is meant to be used with the `make iso` target and not `make image`. Will look at ways to clarify this.

**Comment by ddstreetmicrosoft** [comment]
looks like this is addressed with the comment above, closing.
