### ISSUE TITLE
Mount failed on wsl build CBL-Mariner 1.0-stable

### ISSUE THREAD

**Issue by osmboy** [microsoft/CBL-Mariner#1302]
i tried build CBL-Mariner 1.0-stable on wsl，then occur mount error when i run this 
```shell
root@DESKTOP-3HJMQ9I:/opt/CBL-Mariner/toolkit# make iso REBUILD_TOOLS=y REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/full.json
/opt/CBL-Mariner/toolkit/out/tools/imagepkgfetcher \
        --input=./imageconfigs/full.json \
        --base-dir=./imageconfigs/ \
        --log-level=info \
        --log-file=/opt/CBL-Mariner/build/logs/imggen/imagepkgfetcher.log \
        --rpm-dir=/opt/CBL-Mariner/out/RPMS \
        --tmp-dir=/opt/CBL-Mariner/build/imagegen/full/fetcher_tmp \
        --tdnf-worker=/opt/CBL-Mariner/build/worker/worker_chroot.tar.gz \
        --tls-cert= \
        --tls-key= \
        --repo-file="/opt/CBL-Mariner/toolkit/resources/manifests/package/local.repo"  --repo-file="/opt/CBL-Mariner/toolkit/resources/manifests/package/fetcher.repo"  \
         --use-update-repo \
        --input-summary-file= \
        --output-summary-file=/opt/CBL-Mariner/build/imagegen/full/image_deps.json \
        --output-dir=/opt/CBL-Mariner/build/imagegen/full/package_repo
INFO[0000] Enabling update repo
INFO[0000] Creating cloning environment to populate (/opt/CBL-Mariner/build/imagegen/full/package_repo)
ERRO[0047] Mount failed on (/opt/CBL-Mariner/build/imagegen/full/fetcher_tmp/dev). Error: no such file or directory
WARN[0047] Error creating mountpoints for chroot
WARN[0102] Failed to initialize cloner. Error: no such file or directory
PANI[0102] Failed to initialize RPM repo cloner. Error: no such file or directory
panic: (*logrus.Entry) 0xc00013a0e0

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc000195d50, 0xc0001a1200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ostorage/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x345
github.com/sirupsen/logrus.(*Entry).Log(0xc00013a000, 0x0, 0xc0001e5df0, 0x1, 0x1)
        /home/ostorage/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xf0
github.com/sirupsen/logrus.(*Entry).Logf(0xc00013a000, 0xc000000000, 0x898bce, 0x2f, 0xc0001e5f38, 0x1, 0x1)
        /home/ostorage/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:333 +0xe5
github.com/sirupsen/logrus.(*Logger).Logf(0xc000195d50, 0x7fff00000000, 0x898bce, 0x2f, 0xc0001e5f38, 0x1, 0x1)
        /home/ostorage/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:146 +0x95
github.com/sirupsen/logrus.(*Logger).Panicf(...)
        /home/ostorage/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:187
main.main()
        /opt/CBL-Mariner/toolkit/tools/imagepkgfetcher/imagepkgfetcher.go:63 +0x2ca
/opt/CBL-Mariner/toolkit/scripts/imggen.mk:94: recipe for target '/opt/CBL-Mariner/build/imagegen/full/image_deps.json' failed
make: *** [/opt/CBL-Mariner/build/imagegen/full/image_deps.json] Error 2
```
is WSL not support for CBL-Mariner?

**Comment by PawelWMS** [comment]
Hi there! CBL-Mariner is currently only tested to build on Ubuntu 18.04. Please see: [here](https://github.com/microsoft/CBL-Mariner/blob/1.0/toolkit/docs/building/prerequisites.md).
