### ISSUE TITLE
Django crashes because there are no timezone files in /usr/share/zoneinfo

### ISSUE THREAD

**Issue by jeremydvoss** [microsoft/CBL-Mariner#7523]
**Describe the bug**
Django produces a `ValueError: Incorrect timezone setting: America/Chicago` when run on `mcr.microsoft.com/cbl-mariner/base/python:3.9`. This is because the /usr/share/zoneinfo contains no timezone files. Even setting a `TIME_ZONE` in `settings.py` or turning timezones off with `USE_TZ = False` does not prevent the error. It seems to need timezone files.

**To Reproduce**
1. Create Django dockerfile base on cbl-mariner:
```
FROM mcr.microsoft.com/cbl-mariner/base/python:3.9
...
CMD [ "gunicorn", "django_app.wsgi" ]
```
2. Build container
3. Run container
4. See Error
5. Edit Django app's settings.py with TIME_ZONE = 'utc' and repeat
6. Edit Django app's settings.py with USE_TZ = 'False' and repeat

**Expected behavior**
Django works on cbl-mariner with or without USE_TZ set.

**Screenshots**
```
inprocagent-1 exited with code 0
pythonapp-1    | [2024-01-29 20:41:59 +0000] [1] [INFO] Starting gunicorn 21.2.0
pythonapp-1    | [2024-01-29 20:41:59 +0000] [1] [INFO] Listening at: http://0.0.0.0:8082 (1)
pythonapp-1    | [2024-01-29 20:41:59 +0000] [1] [INFO] Using worker: sync
pythonapp-1    | [2024-01-29 20:41:59 +0000] [17] [INFO] Booting worker with pid: 17
pythonapp-1    | [2024-01-29 20:41:59 +0000] [17] [ERROR] Exception in worker process
pythonapp-1    | Traceback (most recent call last):
pythonapp-1    |   File "/usr/lib/python3.9/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
pythonapp-1    |     worker.init_process()
pythonapp-1    |   File "/usr/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
pythonapp-1    |     self.load_wsgi()
pythonapp-1    |   File "/usr/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
pythonapp-1    |     self.wsgi = self.app.wsgi()
pythonapp-1    |   File "/usr/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
pythonapp-1    |     self.callable = self.load()
pythonapp-1    |   File "/usr/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
pythonapp-1    |     return self.load_wsgiapp()
pythonapp-1    |   File "/usr/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
pythonapp-1    |     return util.import_app(self.app_uri)
pythonapp-1    |   File "/usr/lib/python3.9/site-packages/gunicorn/util.py", line 371, in import_app
pythonapp-1    |     mod = importlib.import_module(module)
pythonapp-1    |   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
pythonapp-1    |     return _bootstrap._gcd_import(name[level:], package, level)
pythonapp-1    |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
pythonapp-1    |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
pythonapp-1    |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
pythonapp-1    |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
pythonapp-1    |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
pythonapp-1    |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
pythonapp-1    |   File "/usr/src/pythonapp/django_app/wsgi.py", line 16, in <module>
pythonapp-1    |     application = get_wsgi_application()
pythonapp-1    |   File "/usr/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
pythonapp-1    |     django.setup(set_prefix=False)
pythonapp-1    |   File "/usr/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
pythonapp-1    |     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
pythonapp-1    |   File "/usr/lib/python3.9/site-packages/django/conf/__init__.py", line 102, in __getattr__
pythonapp-1    |     self._setup(name)
pythonapp-1    |   File "/usr/lib/python3.9/site-packages/django/conf/__init__.py", line 89, in _setup
pythonapp-1    |     self._wrapped = Settings(settings_module)
pythonapp-1    |   File "/usr/lib/python3.9/site-packages/django/conf/__init__.py", line 260, in __init__
pythonapp-1    |     raise ValueError("Incorrect timezone setting: %s" % self.TIME_ZONE)
pythonapp-1    | ValueError: Incorrect timezone setting: America/Chicago
pythonapp-1    | [2024-01-29 20:41:59 +0000] [17] [INFO] Worker exiting (pid: 17)
pythonapp-1    | [2024-01-29 20:41:59 +0000] [1] [ERROR] Worker (pid:17) exited with code 3
pythonapp-1    | [2024-01-29 20:41:59 +0000] [1] [ERROR] Shutting down: Master
pythonapp-1    | [2024-01-29 20:41:59 +0000] [1] [ERROR] Reason: Worker failed to boot.
pythonapp-1 exited with code 3
```

**Comment by jeremydvoss** [comment]
Alternatively, is there a comparable MCR python image I could use instead that does have timezone files?

**Comment by jeremydvoss** [comment]
Related: https://github.com/docker-library/postgres/issues/220

apk add does not work on cbl-mariner, though.

**Comment by jeremydvoss** [comment]
Through trial and error, figured out that mariner uses yum. Adding `RUN yum install -y tzdata` fixed the issue.
